site_name: Meradeb
docs_dir: docs/source/
site_dir: docs/build/
nav:
  - Home: index.md
  - About Meradeb: about_meradeb.md
  - Installation Guide: install_guide.md
  - Setting Up Development Environment: setting_up_development_environment.md
  - Hotkeys: hotkeys.md

theme:
  name: material
