set -g default-terminal 'tmux-256color'
set -as terminal-features ',*:RGB'
# Not rebinding just removing the confirmation before killing pane or window
bind -N "Kill pane" k kill-pane
bind -N "Kill window" & kill-window

# Vi mode for copy
setw -g mode-keys vi
bind -N "Begin selection" -T copy-mode-vi v send -X begin-selection
bind -N "Copy selection" -T copy-mode-vi y send -X copy-selection-and-cancel

set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on
set -as terminal-features ",*:clipboard"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank' 
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'dracula/tmux' 
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'junegunn/fzf'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @treemux-tree-client 'nvim-tree'  # or 'neo-tree'
set -g @treemux-tree-nvim-init-file '~/.tmux/plugins/treemux/configs/treemux_init.lua'
# Set python with pynvim installed.
# Use an absolute path because if you activate a python virtual environment, the pynvim may not be installed on that environment.
set -g @treemux-python-command '/usr/bin/python3'  # default is '/usr/bin/python3'
# If you want to completely isolate the treemux's nvim config and data from your main nvim config and data, set NVIM_APPNAME.
# This will make treemux use '~/.config/nvim-treemux', '~/.local/share/nvim-treemux'
# set -g @treemux-nvim-command 'NVIM_APPNAME=nvim-treemux nvim'  # default is 'nvim'

set -g @plugin 'kiyoon/treemux'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
# set -g @dracula-show-powerline true
# set -g @dracula-plugins "cpu-usage ram-usage time network"
set -g @plugin 'tmux-plugins/tmux-open'

# Make default shell for tmux
set-option -g default-shell /bin/zsh


# For dimming inactive panes, vimade integration
set -g focus-events on

set -g extended-keys on
# Better window renaming 
set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command}'

# Auto-install TPM plugins if missing
run-shell '~/.tmux/plugins/tpm/bin/install_plugins'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
