source ~/.local/share/meradeb/defaults/bash/shell
source ~/.local/share/meradeb/defaults/bash/aliases
source ~/.local/share/meradeb/defaults/bash/functions
source ~/.local/share/meradeb/defaults/bash/prompt
source ~/.local/share/meradeb/defaults/bash/init
