name: "Build and Package"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          podman run --rm -it \
          --name meradeb \
          debian:trixie \
          bash -c '
            apt-get update
            apt-get install -y git curl bc sudo gum expect

            curl -fsSL https://raw.githubusercontent.com/prithvijitguha/meradeb/main/boot.sh -o /tmp/boot.sh
          '
